import {
  Award,
  BadgeCheck,
  ChartLine,
  Gem,
  BarChart3,
  Bell,
  Bot,
  BrainCircuit,
  Briefcase,
  CalendarClock,
  Camera,
  Clapperboard,
  ClipboardList,
  Code,
  Database,
  FileText,
  Gauge,
  Globe,
  Handshake,
  Kanban,
  Languages,
  LayoutDashboard,
  Layers,
  Lightbulb,
  Link2,
  Mail,
  Megaphone,
  MessageSquare,
  MonitorSmartphone,
  Palette,
  PenLine,
  PieChart,
  Rocket,
  Search,
  Share2,
  ShieldCheck,
  ShoppingCart,
  Sparkles,
  Target,
  TrendingUp,
  Users,
  Workflow,
  Zap,
  type LucideIcon,
} from "lucide-react";
import { DEFAULT_ICON, isIconName, type IconName } from "@/lib/icon-names";

/* Panelde seçilen ikon adının bileşeni (liste: src/lib/icon-names.ts) */
const ICONS: Record<IconName, LucideIcon> = {
  share: Share2,
  palette: Palette,
  pen: PenLine,
  monitor: MonitorSmartphone,
  "chart-bar": BarChart3,
  clapperboard: Clapperboard,
  bot: Bot,
  users: Users,
  workflow: Workflow,
  briefcase: Briefcase,
  message: MessageSquare,
  brain: BrainCircuit,
  languages: Languages,
  bell: Bell,
  calendar: CalendarClock,
  clipboard: ClipboardList,
  database: Database,
  file: FileText,
  gauge: Gauge,
  handshake: Handshake,
  kanban: Kanban,
  dashboard: LayoutDashboard,
  layers: Layers,
  link: Link2,
  pie: PieChart,
  shield: ShieldCheck,
  sparkles: Sparkles,
  target: Target,
  rocket: Rocket,
  megaphone: Megaphone,
  camera: Camera,
  globe: Globe,
  cart: ShoppingCart,
  search: Search,
  mail: Mail,
  zap: Zap,
  trending: TrendingUp,
  code: Code,
  lightbulb: Lightbulb,
  award: Award,
  "badge-check": BadgeCheck,
  gem: Gem,
  "chart-line": ChartLine,
};

export function iconFor(name: string | null | undefined): LucideIcon {
  return ICONS[isIconName(name) ? name : DEFAULT_ICON];
}

/** Eski veri kaynağındaki (data.ts / products-content.ts) bileşenin adı */
export function iconNameOf(icon: LucideIcon): IconName {
  const hit = (Object.entries(ICONS) as [IconName, LucideIcon][]).find(([, c]) => c === icon);
  return hit?.[0] ?? DEFAULT_ICON;
}
