/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    leads: Lead;
    bookings: Booking;
    services: Service;
    products: Product;
    posts: Post;
    categories: Category;
    team: Team;
    references: Reference;
    'case-studies': CaseStudy;
    testimonials: Testimonial;
    media: Media;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    leads: LeadsSelect<false> | LeadsSelect<true>;
    bookings: BookingsSelect<false> | BookingsSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    team: TeamSelect<false> | TeamSelect<true>;
    references: ReferencesSelect<false> | ReferencesSelect<true>;
    'case-studies': CaseStudiesSelect<false> | CaseStudiesSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'home-page': HomePage;
    'about-page': AboutPage;
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    'home-page': HomePageSelect<false> | HomePageSelect<true>;
    'about-page': AboutPageSelect<false> | AboutPageSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads".
 */
export interface Lead {
  id: number;
  name: string;
  email: string;
  phone?: string | null;
  service?: string | null;
  subject?: string | null;
  message: string;
  status: 'yeni' | 'iletisim' | 'teklif' | 'kazanildi' | 'kaybedildi';
  source?: string | null;
  /**
   * Yalnız panelde görünür.
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bookings".
 */
export interface Booking {
  id: number;
  name: string;
  email: string;
  phone?: string | null;
  date: string;
  time: '10:00' | '11:00' | '13:00' | '14:00' | '15:00' | '16:00';
  topic?: string | null;
  note?: string | null;
  status: 'bekliyor' | 'onaylandi' | 'tamamlandi' | 'iptal';
  slot?: string | null;
  source?: string | null;
  /**
   * Yalnız panelde görünür.
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  title: string;
  /**
   * Kartlarda ve sayfa girişinde görünen tek cümle.
   */
  short: string;
  /**
   * /hizmetler sayfasındaki kartta görünür.
   */
  cardImage?: (number | null) | Media;
  /**
   * İlk görsel solda büyük, sonraki iki görsel sağda üst üste, kalanlar altta tam genişlikte görünür. Kırpma odağını görselin kendisinden ayarlayabilirsiniz.
   */
  gallery?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  headline: string;
  offeringsTitle: string;
  intro?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Numaralı kartlar olarak sırayla listelenir.
   */
  offerings?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Kapsam metninin altında küçük haplar olarak görünür.
   */
  keywords?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Sayfada iki sütunlu akordeon olarak görünür ve arama motorlarına SSS olarak bildirilir.
   */
  faq?:
    | {
        q: string;
        a: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Ölçülmüş kampanya sonuçları ve Google ödülleri bölümü.
   */
  showCases?: boolean | null;
  /**
   * Tasarlayıp yayına aldığımız sitelerin bağlantı listesi.
   */
  showWebProjects?: boolean | null;
  /**
   * 140-160 karakter önerilir. Boşsa kısa açıklama kullanılır.
   */
  seoDescription?: string | null;
  /**
   * Sayfa adresi: /hizmetler/adres. Yayındaki bir adresi değiştirmek eski bağlantıları kırar.
   */
  slug?: string | null;
  /**
   * Küçük sayı önce gelir (menü, kartlar, alt bilgi).
   */
  order?: number | null;
  icon:
    | 'share'
    | 'palette'
    | 'pen'
    | 'monitor'
    | 'chart-bar'
    | 'clapperboard'
    | 'bot'
    | 'users'
    | 'workflow'
    | 'briefcase'
    | 'message'
    | 'brain'
    | 'languages'
    | 'bell'
    | 'calendar'
    | 'clipboard'
    | 'database'
    | 'file'
    | 'gauge'
    | 'handshake'
    | 'kanban'
    | 'dashboard'
    | 'layers'
    | 'link'
    | 'pie'
    | 'shield'
    | 'sparkles'
    | 'target'
    | 'rocket'
    | 'megaphone'
    | 'camera'
    | 'globe'
    | 'cart'
    | 'search'
    | 'mail'
    | 'zap'
    | 'trending'
    | 'code'
    | 'lightbulb'
    | 'award'
    | 'badge-check'
    | 'gem'
    | 'chart-line';
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Görseli göremeyen ziyaretçi ve arama motorları için kısa açıklama.
   */
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    wide?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  name: string;
  tagline: string;
  /**
   * Ana sayfa ve /urunler kartlarında görünür.
   */
  desc: string;
  /**
   * Kartta tik işaretiyle listelenir; üç madde önerilir.
   */
  highlights?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Yatay ürün ekranı (1600x1100 önerilir). Alternatif metni medya kaydından gelir.
   */
  screenshot: number | Media;
  hero: {
    /**
     * Boşsa ürün adı kullanılır.
     */
    eyebrow?: string | null;
    /**
     * Yıldız içindeki kelime bir kademe kalın yazılır: Müşterinize *7/24* yanıt veren asistan
     */
    headline: string;
    sub: string;
    ctaLabel?: string | null;
  };
  /**
   * İkonlu kartlar; altı özellik önerilir.
   */
  features?:
    | {
        title: string;
        icon:
          | 'share'
          | 'palette'
          | 'pen'
          | 'monitor'
          | 'chart-bar'
          | 'clapperboard'
          | 'bot'
          | 'users'
          | 'workflow'
          | 'briefcase'
          | 'message'
          | 'brain'
          | 'languages'
          | 'bell'
          | 'calendar'
          | 'clipboard'
          | 'database'
          | 'file'
          | 'gauge'
          | 'handshake'
          | 'kanban'
          | 'dashboard'
          | 'layers'
          | 'link'
          | 'pie'
          | 'shield'
          | 'sparkles'
          | 'target'
          | 'rocket'
          | 'megaphone'
          | 'camera'
          | 'globe'
          | 'cart'
          | 'search'
          | 'mail'
          | 'zap'
          | 'trending'
          | 'code'
          | 'lightbulb'
          | 'award'
          | 'badge-check'
          | 'gem'
          | 'chart-line';
        desc: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Numaralı kartlar; dört adım önerilir.
   */
  steps?:
    | {
        title: string;
        desc: string;
        id?: string | null;
      }[]
    | null;
  useCases?:
    | {
        title: string;
        desc: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Yalnız ürün ve kurulum ifadeleri (kanal sayısı, kurulum süresi). Kaynağı olmayan performans yüzdesi yazmayın.
   */
  stats?:
    | {
        value: number;
        /**
         * %, /7, gün…
         */
        suffix?: string | null;
        label: string;
        id?: string | null;
      }[]
    | null;
  integrations?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Sayfada iki sütunlu akordeon olarak görünür ve arama motorlarına SSS olarak bildirilir.
   */
  faq?:
    | {
        q: string;
        a: string;
        id?: string | null;
      }[]
    | null;
  seo?: {
    /**
     * Boşsa ürün adı ve slogan.
     */
    title?: string | null;
    description?: string | null;
    keywords?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Sayfa adresi: /urunler/adres. Yayındaki bir adresi değiştirmek eski bağlantıları kırar.
   */
  slug?: string | null;
  /**
   * Küçük sayı önce gelir (menü, kartlar, alt bilgi).
   */
  order?: number | null;
  icon:
    | 'share'
    | 'palette'
    | 'pen'
    | 'monitor'
    | 'chart-bar'
    | 'clapperboard'
    | 'bot'
    | 'users'
    | 'workflow'
    | 'briefcase'
    | 'message'
    | 'brain'
    | 'languages'
    | 'bell'
    | 'calendar'
    | 'clipboard'
    | 'database'
    | 'file'
    | 'gauge'
    | 'handshake'
    | 'kanban'
    | 'dashboard'
    | 'layers'
    | 'link'
    | 'pie'
    | 'shield'
    | 'sparkles'
    | 'target'
    | 'rocket'
    | 'megaphone'
    | 'camera'
    | 'globe'
    | 'cart'
    | 'search'
    | 'mail'
    | 'zap'
    | 'trending'
    | 'code'
    | 'lightbulb'
    | 'award'
    | 'badge-check'
    | 'gem'
    | 'chart-line';
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  /**
   * Liste kartında ve paylaşımlarda görünen 1-2 cümle.
   */
  excerpt: string;
  /**
   * Yatay görsel önerilir (en az 1600 px genişlik).
   */
  cover?: (number | null) | Media;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Boş bırakırsanız başlıktan üretilir: /blog/adres
   */
  slug?: string | null;
  category?: (number | null) | Category;
  /**
   * Boş bırakılırsa yayınlandığı an yazılır.
   */
  publishedAt?: string | null;
  author?: (number | null) | User;
  /**
   * Boş bırakılırsa başlık ve özet kullanılır.
   */
  seo?: {
    title?: string | null;
    description?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  title: string;
  /**
   * Boş bırakırsanız addan üretilir.
   */
  slug?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  /**
   * Editör içerik ve müşteri kayıtlarıyla çalışır; kullanıcı ekleme ve silme yöneticidedir.
   */
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Fotoğraf yüklenmeyen kişi için marka renklerinde yer tutucu görünür.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team".
 */
export interface Team {
  id: number;
  name: string;
  role: string;
  /**
   * Dikey portre önerilir (4:5). Yüz odağını görselin kendisinden ayarlayabilirsiniz.
   */
  photo?: (number | null) | Media;
  linkedin?: string | null;
  /**
   * Küçük sayı önce gelir (menü, kartlar, alt bilgi).
   */
  order?: number | null;
  showOnHome?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Logolar şeritte gri tonda ve aynı yükseklikte gösterilir; şeffaf zeminli SVG ya da PNG önerilir.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "references".
 */
export interface Reference {
  id: number;
  name: string;
  logo?: (number | null) | Media;
  /**
   * Küçük sayı önce gelir (menü, kartlar, alt bilgi).
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Yalnız ölçülmüş ve müşterinin paylaşmayı onayladığı sonuçları yazın.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "case-studies".
 */
export interface CaseStudy {
  id: number;
  sector: string;
  title: string;
  summary: string;
  /**
   * "Kartta göster" seçili ilk üç sonuç kartta görünür; hiçbiri seçili değilse ilk üçü.
   */
  stats?:
    | {
        label: string;
        value: number;
        prefix?: string | null;
        suffix?: string | null;
        featured?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Kartın altında küçük yazı: ölçüm süresi, koşul vb.
   */
  note?: string | null;
  /**
   * Küçük sayı önce gelir (menü, kartlar, alt bilgi).
   */
  order?: number | null;
  showOnHome?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Yorum metni, kişiden yazılı yayın izni alınıp işaretlenene kadar sitede görünmez.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  quote?: string | null;
  name: string;
  title?: string | null;
  company?: string | null;
  photo?: (number | null) | Media;
  /**
   * Kişinin adı ve yorumu için yazılı izin alındıysa işaretleyin.
   */
  consent?: boolean | null;
  /**
   * Küçük sayı önce gelir (menü, kartlar, alt bilgi).
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'leads';
        value: number | Lead;
      } | null)
    | ({
        relationTo: 'bookings';
        value: number | Booking;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'team';
        value: number | Team;
      } | null)
    | ({
        relationTo: 'references';
        value: number | Reference;
      } | null)
    | ({
        relationTo: 'case-studies';
        value: number | CaseStudy;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads_select".
 */
export interface LeadsSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  phone?: T;
  service?: T;
  subject?: T;
  message?: T;
  status?: T;
  source?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bookings_select".
 */
export interface BookingsSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  phone?: T;
  date?: T;
  time?: T;
  topic?: T;
  note?: T;
  status?: T;
  slot?: T;
  source?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  title?: T;
  short?: T;
  cardImage?: T;
  gallery?:
    | T
    | {
        image?: T;
        id?: T;
      };
  headline?: T;
  offeringsTitle?: T;
  intro?:
    | T
    | {
        text?: T;
        id?: T;
      };
  offerings?:
    | T
    | {
        text?: T;
        id?: T;
      };
  keywords?:
    | T
    | {
        text?: T;
        id?: T;
      };
  faq?:
    | T
    | {
        q?: T;
        a?: T;
        id?: T;
      };
  showCases?: T;
  showWebProjects?: T;
  seoDescription?: T;
  slug?: T;
  order?: T;
  icon?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  name?: T;
  tagline?: T;
  desc?: T;
  highlights?:
    | T
    | {
        text?: T;
        id?: T;
      };
  screenshot?: T;
  hero?:
    | T
    | {
        eyebrow?: T;
        headline?: T;
        sub?: T;
        ctaLabel?: T;
      };
  features?:
    | T
    | {
        title?: T;
        icon?: T;
        desc?: T;
        id?: T;
      };
  steps?:
    | T
    | {
        title?: T;
        desc?: T;
        id?: T;
      };
  useCases?:
    | T
    | {
        title?: T;
        desc?: T;
        id?: T;
      };
  stats?:
    | T
    | {
        value?: T;
        suffix?: T;
        label?: T;
        id?: T;
      };
  integrations?:
    | T
    | {
        text?: T;
        id?: T;
      };
  faq?:
    | T
    | {
        q?: T;
        a?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        keywords?:
          | T
          | {
              text?: T;
              id?: T;
            };
      };
  slug?: T;
  order?: T;
  icon?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  excerpt?: T;
  cover?: T;
  content?: T;
  slug?: T;
  category?: T;
  publishedAt?: T;
  author?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team_select".
 */
export interface TeamSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  photo?: T;
  linkedin?: T;
  order?: T;
  showOnHome?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "references_select".
 */
export interface ReferencesSelect<T extends boolean = true> {
  name?: T;
  logo?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "case-studies_select".
 */
export interface CaseStudiesSelect<T extends boolean = true> {
  sector?: T;
  title?: T;
  summary?: T;
  stats?:
    | T
    | {
        label?: T;
        value?: T;
        prefix?: T;
        suffix?: T;
        featured?: T;
        id?: T;
      };
  note?: T;
  order?: T;
  showOnHome?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  quote?: T;
  name?: T;
  title?: T;
  company?: T;
  photo?: T;
  consent?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        wide?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Kaydettiğinizde ana sayfa hemen güncellenir.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page".
 */
export interface HomePage {
  id: number;
  hero: {
    /**
     * Yıldız içindeki kelime bir kademe kalın yazılır: Markanızı bir üst seviyeye *taşıyoruz*
     */
    title: string;
    sub: string;
    showServiceLinks?: boolean | null;
    primaryLabel: string;
    primaryHref: string;
    secondaryLabel: string;
    secondaryHref: string;
    badgeStrong?: string | null;
    /**
     * {sayı} yazdığınız yere referans sayısı gelir.
     */
    badgeText?: string | null;
  };
  references: {
    show?: boolean | null;
    title: string;
    lead?: string | null;
  };
  services: {
    show?: boolean | null;
    title: string;
    /**
     * {sayı} yazdığınız yere hizmet sayısı yazıyla gelir (altı, yedi…).
     */
    lead?: string | null;
  };
  products: {
    show?: boolean | null;
    title: string;
    lead?: string | null;
  };
  video: {
    show?: boolean | null;
    title: string;
    lead?: string | null;
  };
  cases: {
    show?: boolean | null;
    title: string;
    lead?: string | null;
  };
  team: {
    show?: boolean | null;
    title: string;
    lead?: string | null;
    /**
     * Ekip kayıtlarında "Ana sayfada göster" seçili olanlar sırayla gösterilir.
     */
    limit?: number | null;
  };
  quotes: {
    show?: boolean | null;
    title: string;
    lead?: string | null;
  };
  faq: {
    show?: boolean | null;
    title: string;
    items?:
      | {
          q: string;
          a: string;
          id?: string | null;
        }[]
      | null;
  };
  meet: {
    title: string;
    text: string;
    buttonLabel: string;
    buttonHref: string;
  };
  seo?: {
    title?: string | null;
    description?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Kaydettiğinizde Hakkımızda sayfası ve ödüllerin geçtiği yerler güncellenir.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page".
 */
export interface AboutPage {
  id: number;
  intro: {
    eyebrow?: string | null;
    title: string;
    lead?: string | null;
    primaryLabel: string;
    primaryHref: string;
    secondaryLabel?: string | null;
    secondaryHref?: string | null;
  };
  story: {
    title: string;
    paragraphs?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    valuesLabel?: string | null;
    values?:
      | {
          title: string;
          icon:
            | 'share'
            | 'palette'
            | 'pen'
            | 'monitor'
            | 'chart-bar'
            | 'clapperboard'
            | 'bot'
            | 'users'
            | 'workflow'
            | 'briefcase'
            | 'message'
            | 'brain'
            | 'languages'
            | 'bell'
            | 'calendar'
            | 'clipboard'
            | 'database'
            | 'file'
            | 'gauge'
            | 'handshake'
            | 'kanban'
            | 'dashboard'
            | 'layers'
            | 'link'
            | 'pie'
            | 'shield'
            | 'sparkles'
            | 'target'
            | 'rocket'
            | 'megaphone'
            | 'camera'
            | 'globe'
            | 'cart'
            | 'search'
            | 'mail'
            | 'zap'
            | 'trending'
            | 'code'
            | 'lightbulb'
            | 'award'
            | 'badge-check'
            | 'gem'
            | 'chart-line';
          desc: string;
          id?: string | null;
        }[]
      | null;
  };
  awards: {
    show?: boolean | null;
    title: string;
    lead?: string | null;
    /**
     * İlk ödül alt bilgideki rozette de görünür (ör. 2025 Google Partner).
     */
    items?:
      | {
          title: string;
          year: string;
          badge?: string | null;
          icon:
            | 'share'
            | 'palette'
            | 'pen'
            | 'monitor'
            | 'chart-bar'
            | 'clapperboard'
            | 'bot'
            | 'users'
            | 'workflow'
            | 'briefcase'
            | 'message'
            | 'brain'
            | 'languages'
            | 'bell'
            | 'calendar'
            | 'clipboard'
            | 'database'
            | 'file'
            | 'gauge'
            | 'handshake'
            | 'kanban'
            | 'dashboard'
            | 'layers'
            | 'link'
            | 'pie'
            | 'shield'
            | 'sparkles'
            | 'target'
            | 'rocket'
            | 'megaphone'
            | 'camera'
            | 'globe'
            | 'cart'
            | 'search'
            | 'mail'
            | 'zap'
            | 'trending'
            | 'code'
            | 'lightbulb'
            | 'award'
            | 'badge-check'
            | 'gem'
            | 'chart-line';
          desc: string;
          image?: (number | null) | Media;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Kişiler "Kurumsal > Ekip"ten gelir.
   */
  team: {
    show?: boolean | null;
    title: string;
    lead?: string | null;
  };
  /**
   * Sayılar referans, hizmet ve ürün kayıtlarından otomatik hesaplanır.
   */
  stats: {
    show?: boolean | null;
    title: string;
    referencesLabel?: string | null;
    servicesLabel?: string | null;
    productsLabel?: string | null;
  };
  closing: {
    title: string;
    lead?: string | null;
    primaryLabel: string;
  };
  seo?: {
    title?: string | null;
    description?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  announcement?: {
    enabled?: boolean | null;
    text?: string | null;
  };
  contact?: {
    email?: string | null;
    phone?: string | null;
    /**
     * Ülke koduyla; doldurulunca sağdaki sekme WhatsApp'a gider.
     */
    whatsapp?: string | null;
    instagram?: string | null;
    address?: string | null;
  };
  /**
   * Çerezsiz, kişisel veri toplamayan ziyaretçi sayımı. Bu alanlar sitenin her sayfasına bir betik eklediği için yalnız yöneticiler düzenleyebilir. API bağlantısı (panel istatistikleri) sunucu ortam değişkenlerindedir.
   */
  analytics?: {
    enabled?: boolean | null;
    websiteId?: string | null;
    scriptUrl?: string | null;
    /**
     * Virgülle ayırın. Doluysa önizleme ve yerel adresler sayılmaz.
     */
    domains?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        title?: T;
        sub?: T;
        showServiceLinks?: T;
        primaryLabel?: T;
        primaryHref?: T;
        secondaryLabel?: T;
        secondaryHref?: T;
        badgeStrong?: T;
        badgeText?: T;
      };
  references?:
    | T
    | {
        show?: T;
        title?: T;
        lead?: T;
      };
  services?:
    | T
    | {
        show?: T;
        title?: T;
        lead?: T;
      };
  products?:
    | T
    | {
        show?: T;
        title?: T;
        lead?: T;
      };
  video?:
    | T
    | {
        show?: T;
        title?: T;
        lead?: T;
      };
  cases?:
    | T
    | {
        show?: T;
        title?: T;
        lead?: T;
      };
  team?:
    | T
    | {
        show?: T;
        title?: T;
        lead?: T;
        limit?: T;
      };
  quotes?:
    | T
    | {
        show?: T;
        title?: T;
        lead?: T;
      };
  faq?:
    | T
    | {
        show?: T;
        title?: T;
        items?:
          | T
          | {
              q?: T;
              a?: T;
              id?: T;
            };
      };
  meet?:
    | T
    | {
        title?: T;
        text?: T;
        buttonLabel?: T;
        buttonHref?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page_select".
 */
export interface AboutPageSelect<T extends boolean = true> {
  intro?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        lead?: T;
        primaryLabel?: T;
        primaryHref?: T;
        secondaryLabel?: T;
        secondaryHref?: T;
      };
  story?:
    | T
    | {
        title?: T;
        paragraphs?:
          | T
          | {
              text?: T;
              id?: T;
            };
        valuesLabel?: T;
        values?:
          | T
          | {
              title?: T;
              icon?: T;
              desc?: T;
              id?: T;
            };
      };
  awards?:
    | T
    | {
        show?: T;
        title?: T;
        lead?: T;
        items?:
          | T
          | {
              title?: T;
              year?: T;
              badge?: T;
              icon?: T;
              desc?: T;
              image?: T;
              id?: T;
            };
      };
  team?:
    | T
    | {
        show?: T;
        title?: T;
        lead?: T;
      };
  stats?:
    | T
    | {
        show?: T;
        title?: T;
        referencesLabel?: T;
        servicesLabel?: T;
        productsLabel?: T;
      };
  closing?:
    | T
    | {
        title?: T;
        lead?: T;
        primaryLabel?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  announcement?:
    | T
    | {
        enabled?: T;
        text?: T;
      };
  contact?:
    | T
    | {
        email?: T;
        phone?: T;
        whatsapp?: T;
        instagram?: T;
        address?: T;
      };
  analytics?:
    | T
    | {
        enabled?: T;
        websiteId?: T;
        scriptUrl?: T;
        domains?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}