/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    leads: Lead;
    bookings: Booking;
    deals: Deal;
    contacts: Contact;
    companies: Company;
    quotes: Quote;
    activities: Activity;
    projects: Project;
    tasks: Task;
    templates: Template;
    conversations: Conversation;
    knowledge: Knowledge;
    'chat-messages': ChatMessage;
    team: Team;
    'case-studies': CaseStudy;
    testimonials: Testimonial;
    references: Reference;
    services: Service;
    products: Product;
    posts: Post;
    media: Media;
    categories: Category;
    users: User;
    tenants: Tenant;
    'payload-kv': PayloadKv;
    'payload-folders': FolderInterface;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    'payload-folders': {
      documentsAndFolders: 'payload-folders' | 'media';
    };
  };
  collectionsSelect: {
    leads: LeadsSelect<false> | LeadsSelect<true>;
    bookings: BookingsSelect<false> | BookingsSelect<true>;
    deals: DealsSelect<false> | DealsSelect<true>;
    contacts: ContactsSelect<false> | ContactsSelect<true>;
    companies: CompaniesSelect<false> | CompaniesSelect<true>;
    quotes: QuotesSelect<false> | QuotesSelect<true>;
    activities: ActivitiesSelect<false> | ActivitiesSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    tasks: TasksSelect<false> | TasksSelect<true>;
    templates: TemplatesSelect<false> | TemplatesSelect<true>;
    conversations: ConversationsSelect<false> | ConversationsSelect<true>;
    knowledge: KnowledgeSelect<false> | KnowledgeSelect<true>;
    'chat-messages': ChatMessagesSelect<false> | ChatMessagesSelect<true>;
    team: TeamSelect<false> | TeamSelect<true>;
    'case-studies': CaseStudiesSelect<false> | CaseStudiesSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    references: ReferencesSelect<false> | ReferencesSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    tenants: TenantsSelect<false> | TenantsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-folders': PayloadFoldersSelect<false> | PayloadFoldersSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'home-page': HomePage;
    'about-page': AboutPage;
    'chatbot-settings': ChatbotSetting;
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    'home-page': HomePageSelect<false> | HomePageSelect<true>;
    'about-page': AboutPageSelect<false> | AboutPageSelect<true>;
    'chatbot-settings': ChatbotSettingsSelect<false> | ChatbotSettingsSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads".
 */
export interface Lead {
  id: number;
  name: string;
  email: string;
  phone?: string | null;
  service?: string | null;
  subject?: string | null;
  message: string;
  status: 'yeni' | 'iletisim' | 'teklif' | 'kazanildi' | 'kaybedildi';
  source?: string | null;
  contact?: (number | null) | Contact;
  deal?: (number | null) | Deal;
  /**
   * Yalnız panelde görünür.
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Görüştüğünüz kişiler. Siteden talep ya da randevu bırakan herkes e-posta adresine göre buraya eklenir.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contacts".
 */
export interface Contact {
  id: number;
  name: string;
  title?: string | null;
  email?: string | null;
  phone?: string | null;
  company?: (number | null) | Company;
  notes?: string | null;
  source?: ('form' | 'randevu' | 'chatbot' | 'referans' | 'manuel') | null;
  /**
   * Yazıp Enter'a basın (ör. e-ticaret, sıcak).
   */
  tags?: string[] | null;
  owner?: (number | null) | User;
  tenant?: (number | null) | Tenant;
  updatedAt: string;
  createdAt: string;
}
/**
 * Müşteri ve aday firmalar. Kişiler ve fırsatlar firmaya bağlanır.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "companies".
 */
export interface Company {
  id: number;
  name: string;
  sector?: string | null;
  website?: string | null;
  phone?: string | null;
  email?: string | null;
  address?: string | null;
  taxOffice?: string | null;
  /**
   * Teklif belgesinde müşteri bilgisi olarak görünür.
   */
  taxNumber?: string | null;
  notes?: string | null;
  owner?: (number | null) | User;
  tenant?: (number | null) | Tenant;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  /**
   * Guru Operation ekip planındaki doluluk yüzdesi bu saate göre hesaplanır.
   */
  weeklyHours?: number | null;
  /**
   * Editör içerik ve müşteri kayıtlarıyla çalışır; kullanıcı ekleme ve silme yöneticidedir.
   */
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Paneli kullanan işletmeler. Bugün yalnız Guru Dijital.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants".
 */
export interface Tenant {
  id: number;
  name: string;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Satışa dönüşebilecek her iş. Aşamaları Satış hattı panosunda sürükleyerek değiştirebilirsiniz.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "deals".
 */
export interface Deal {
  id: number;
  title: string;
  contact?: (number | null) | Contact;
  /**
   * Boşsa kişinin firması.
   */
  company?: (number | null) | Company;
  value?: number | null;
  expectedClose?: string | null;
  service?: string | null;
  /**
   * Fiyat, zamanlama, rakip… Sonraki teklifler için ipucu.
   */
  lostReason?: string | null;
  notes?: string | null;
  stage: 'aday' | 'gorusme' | 'teklif' | 'kazanildi' | 'kaybedildi';
  owner?: (number | null) | User;
  lead?: (number | null) | Lead;
  closedAt?: string | null;
  order?: number | null;
  tenant?: (number | null) | Tenant;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bookings".
 */
export interface Booking {
  id: number;
  name: string;
  email: string;
  phone?: string | null;
  date: string;
  time: '10:00' | '11:00' | '13:00' | '14:00' | '15:00' | '16:00';
  topic?: string | null;
  note?: string | null;
  status: 'bekliyor' | 'onaylandi' | 'tamamlandi' | 'iptal';
  slot?: string | null;
  source?: string | null;
  contact?: (number | null) | Contact;
  deal?: (number | null) | Deal;
  /**
   * Yalnız panelde görünür.
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Kalem kalem teklif; toplamlar kendiliğinden hesaplanır. Kaydettikten sonra "Yazdır / PDF" ile müşteriye gönderilecek belge açılır.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quotes".
 */
export interface Quote {
  id: number;
  title: string;
  deal?: (number | null) | Deal;
  contact?: (number | null) | Contact;
  company?: (number | null) | Company;
  items?:
    | {
        description: string;
        qty: number;
        unit?: string | null;
        unitPrice: number;
        vatRate: '20' | '10' | '1' | '0';
        id?: string | null;
      }[]
    | null;
  /**
   * Belgede kalemlerin altında görünür: kapsam, teslim süresi, dahil olmayanlar.
   */
  notes?: string | null;
  terms?: string | null;
  /**
   * Kaydedince verilir (GD-yıl-sıra).
   */
  number?: string | null;
  status: 'taslak' | 'gonderildi' | 'kabul' | 'red';
  issueDate?: string | null;
  validUntil?: string | null;
  subtotal?: number | null;
  vatTotal?: number | null;
  total?: number | null;
  owner?: (number | null) | User;
  tenant?: (number | null) | Tenant;
  updatedAt: string;
  createdAt: string;
}
/**
 * Arama, toplantı, not ve görevler. Kişi, firma ya da fırsat sayfasının altından da hızlıca eklenir.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "activities".
 */
export interface Activity {
  id: number;
  type: 'not' | 'arama' | 'eposta' | 'toplanti' | 'gorev' | 'sistem';
  title: string;
  body?: string | null;
  /**
   * Görev ve toplantılarda.
   */
  dueAt?: string | null;
  done?: boolean | null;
  deal?: (number | null) | Deal;
  contact?: (number | null) | Contact;
  company?: (number | null) | Company;
  booking?: (number | null) | Booking;
  owner?: (number | null) | User;
  tenant?: (number | null) | Tenant;
  updatedAt: string;
  createdAt: string;
}
/**
 * Müşteri işleri ve iç projeler. Şablon seçerek açarsanız görevler kendiliğinden oluşur.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  title: string;
  company?: (number | null) | Company;
  contact?: (number | null) | Contact;
  startDate?: string | null;
  /**
   * Şablonla açılırsa son adımın bitişi.
   */
  dueDate?: string | null;
  /**
   * Yalnız iş açılırken uygulanır: adımlar görev olarak eklenir.
   */
  template?: (number | null) | Template;
  description?: string | null;
  status: 'aktif' | 'beklemede' | 'tamamlandi' | 'iptal';
  /**
   * Şablon adımında sorumlu yoksa görev buna atanır; Kontrol'e gelen işler ona bildirilir.
   */
  owner?: (number | null) | User;
  deal?: (number | null) | Deal;
  tenant?: (number | null) | Tenant;
  updatedAt: string;
  createdAt: string;
}
/**
 * Tekrarlayan işlerin adımları. Şablondan iş açınca her adım sorumlusuna ve tarihine göre görev olur.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "templates".
 */
export interface Template {
  id: number;
  name: string;
  description?: string | null;
  /**
   * Başlangıç ve süre iş günüdür: işin başladığı günden kaç gün sonra başlar, kaç günde biter.
   */
  steps?:
    | {
        title: string;
        assignee?: (number | null) | User;
        offset: number;
        duration: number;
        /**
         * Ekip kapasitesi bu saatle hesaplanır.
         */
        hours?: number | null;
        priority?: ('dusuk' | 'normal' | 'yuksek' | 'acil') | null;
        checklist?:
          | {
              text: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  tenant?: (number | null) | Tenant;
  updatedAt: string;
  createdAt: string;
}
/**
 * Operasyon görevleri. Görev panosunda sürükleyerek aşamasını değiştirebilirsiniz; Tamam'a yalnız Kontrol'den ve kontrol listesi bitince geçilir.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tasks".
 */
export interface Task {
  id: number;
  title: string;
  project?: (number | null) | Project;
  assignee?: (number | null) | User;
  startDate?: string | null;
  dueDate?: string | null;
  /**
   * Ekip planındaki doluluk bununla hesaplanır.
   */
  hours?: number | null;
  description?: string | null;
  /**
   * Açık madde varken görev Tamam'a geçmez.
   */
  checklist?:
    | {
        done?: boolean | null;
        text: string;
        id?: string | null;
      }[]
    | null;
  stage: 'yapilacak' | 'devam' | 'kontrol' | 'tamam';
  priority: 'dusuk' | 'normal' | 'yuksek' | 'acil';
  /**
   * Panoda G-numara olarak görünür.
   */
  seq?: number | null;
  startedAt?: string | null;
  completedAt?: string | null;
  order?: number | null;
  tenant?: (number | null) | Tenant;
  updatedAt: string;
  createdAt: string;
}
/**
 * Sitedeki sohbetler. Yanıtlamak için menüdeki Sohbetler ekranını kullanın.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "conversations".
 */
export interface Conversation {
  id: number;
  label?: string | null;
  name?: string | null;
  email?: string | null;
  phone?: string | null;
  /**
   * Asistan sohbetin konusunu kendisi etiketler.
   */
  topic?: string | null;
  page?: string | null;
  lastText?: string | null;
  status: 'bot' | 'ekip' | 'kapali';
  needsReply?: boolean | null;
  assignee?: (number | null) | User;
  contact?: (number | null) | Contact;
  lead?: (number | null) | Lead;
  booking?: (number | null) | Booking;
  lastMessageAt?: string | null;
  handedOffAt?: string | null;
  firstTeamReplyAt?: string | null;
  visitorMessages?: number | null;
  token?: string | null;
  tenant?: (number | null) | Tenant;
  updatedAt: string;
  createdAt: string;
}
/**
 * Asistan hizmetleri, ürünleri, sık sorulan soruları ve iletişim bilgilerini sitenin kendisinden okur. Sitede olmayan bilgileri (çalışma saatleri, ödeme koşulları, kampanyalar) buraya ekleyin.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "knowledge".
 */
export interface Knowledge {
  id: number;
  title: string;
  /**
   * Asistan bunu olduğu gibi bilgi olarak kullanır; kısa ve net yazın.
   */
  content: string;
  active?: boolean | null;
  tenant?: (number | null) | Tenant;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "chat-messages".
 */
export interface ChatMessage {
  id: number;
  conversation: number | Conversation;
  role: 'ziyaretci' | 'bot' | 'ekip' | 'sistem';
  text: string;
  author?: (number | null) | User;
  unanswered?: boolean | null;
  tenant?: (number | null) | Tenant;
  updatedAt: string;
  createdAt: string;
}
/**
 * Fotoğraf yüklenmeyen kişi için marka renklerinde yer tutucu görünür.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team".
 */
export interface Team {
  id: number;
  name: string;
  role: string;
  /**
   * Dikey portre önerilir (4:5). Yüz odağını görselin kendisinden ayarlayabilirsiniz.
   */
  photo?: (number | null) | Media;
  linkedin?: string | null;
  /**
   * Küçük sayı önce gelir (menü, kartlar, alt bilgi).
   */
  order?: number | null;
  showOnHome?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Görseli göremeyen ziyaretçi ve arama motorları için kısa açıklama (ör. "Guru CRM satış hattı ekranı").
   */
  alt: string;
  prefix?: string | null;
  _objectKey?: string | null;
  folder?: (number | null) | FolderInterface;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    wide?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders".
 */
export interface FolderInterface {
  id: number;
  name: string;
  folder?: (number | null) | FolderInterface;
  documentsAndFolders?: {
    docs?: (
      | {
          relationTo?: 'payload-folders';
          value: number | FolderInterface;
        }
      | {
          relationTo?: 'media';
          value: number | Media;
        }
    )[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  folderType?: 'media'[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Yalnız ölçülmüş ve müşterinin paylaşmayı onayladığı sonuçları yazın.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "case-studies".
 */
export interface CaseStudy {
  id: number;
  sector: string;
  title: string;
  summary: string;
  /**
   * "Kartta göster" seçili ilk üç sonuç kartta görünür; hiçbiri seçili değilse ilk üçü.
   */
  stats?:
    | {
        label: string;
        value: number;
        prefix?: string | null;
        suffix?: string | null;
        featured?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Kartın altında küçük yazı: ölçüm süresi, koşul vb.
   */
  note?: string | null;
  /**
   * Küçük sayı önce gelir (menü, kartlar, alt bilgi).
   */
  order?: number | null;
  showOnHome?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Yorum metni, kişiden yazılı yayın izni alınıp işaretlenene kadar sitede görünmez.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  quote?: string | null;
  name: string;
  title?: string | null;
  company?: string | null;
  photo?: (number | null) | Media;
  /**
   * Kişinin adı ve yorumu için yazılı izin alındıysa işaretleyin.
   */
  consent?: boolean | null;
  /**
   * Küçük sayı önce gelir (menü, kartlar, alt bilgi).
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Logolar şeritte gri tonda ve aynı yükseklikte gösterilir; şeffaf zeminli SVG ya da PNG önerilir.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "references".
 */
export interface Reference {
  id: number;
  name: string;
  logo?: (number | null) | Media;
  /**
   * Küçük sayı önce gelir (menü, kartlar, alt bilgi).
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  title: string;
  /**
   * Kartlarda ve sayfa girişinde görünen tek cümle.
   */
  short: string;
  /**
   * Üst menüde hizmet adının altındaki kısa satır.
   */
  menuDesc?: string | null;
  /**
   * /hizmetler sayfasındaki kartta görünür.
   */
  cardImage?: (number | null) | Media;
  /**
   * İlk görsel solda büyük, sonraki iki görsel sağda üst üste görünür. Kalanlardan yalnız yatay bant biçimindekiler (en az 2:1, ör. logo şeridi) altta tam genişlikte basılır. Video Tasarımı sayfasında ana karede tanıtım videosu durur, görseller yana geçer. Kırpma odağını görselin kendisinden ayarlayabilirsiniz.
   */
  gallery?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  headline: string;
  offeringsTitle: string;
  intro?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Numaralı kartlar olarak sırayla listelenir.
   */
  offerings?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Kapsam metninin altında küçük haplar olarak görünür. Büyük harfle başlayın (ör. İçerik planı, Meta Ads).
   */
  keywords?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Sayfada iki sütunlu akordeon olarak görünür ve arama motorlarına SSS olarak bildirilir.
   */
  faq?:
    | {
        q: string;
        a: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Ölçülmüş kampanya sonuçları ve Google ödülleri bölümü.
   */
  showCases?: boolean | null;
  /**
   * Tasarlayıp yayına aldığımız sitelerin bağlantı listesi.
   */
  showWebProjects?: boolean | null;
  /**
   * 140-160 karakter önerilir. Boşsa kısa açıklama kullanılır.
   */
  seoDescription?: string | null;
  /**
   * Sayfa adresi: /hizmetler/adres. Yayındaki bir adresi değiştirmek eski bağlantıları kırar.
   */
  slug?: string | null;
  /**
   * Küçük sayı önce gelir (menü, kartlar, alt bilgi).
   */
  order?: number | null;
  icon:
    | 'share'
    | 'palette'
    | 'pen'
    | 'monitor'
    | 'chart-bar'
    | 'clapperboard'
    | 'bot'
    | 'users'
    | 'workflow'
    | 'briefcase'
    | 'message'
    | 'brain'
    | 'languages'
    | 'bell'
    | 'calendar'
    | 'clipboard'
    | 'database'
    | 'file'
    | 'gauge'
    | 'handshake'
    | 'kanban'
    | 'dashboard'
    | 'layers'
    | 'link'
    | 'pie'
    | 'shield'
    | 'sparkles'
    | 'target'
    | 'rocket'
    | 'megaphone'
    | 'camera'
    | 'globe'
    | 'cart'
    | 'search'
    | 'mail'
    | 'zap'
    | 'trending'
    | 'code'
    | 'lightbulb'
    | 'award'
    | 'badge-check'
    | 'gem'
    | 'chart-line';
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  name: string;
  tagline: string;
  /**
   * Ana sayfa ve ürünler sayfasındaki kartlarda görünür.
   */
  desc: string;
  hero: {
    /**
     * Başlığın üstündeki küçük etiket. Boşsa ürün adı yazar.
     */
    eyebrow?: string | null;
    headline: string;
    sub: string;
    ctaLabel?: string | null;
    /**
     * Düğmelerin altında tik işaretiyle; yalnız taahhüt ettiğiniz bilgiler (ör. Standart kurulum aynı gün).
     */
    trust?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Başlığın yanında duran yatay görsel (4:3).
   */
  heroVisual?: (number | null) | Media;
  tour?: {
    show?: boolean | null;
    title?: string | null;
    /**
     * Site içindeki dosya (/video/products/guru-chatbot.mp4) ya da https ile başlayan mp4 adresi.
     */
    videoUrl?: string | null;
    /**
     * Oynat düğmesinin arkasındaki kare. Boşsa videonun hazır kapağı kullanılır.
     */
    poster?: (number | null) | Media;
  };
  /**
   * Görsel ve metin dönüşümlü satırlar; üç satır önerilir.
   */
  showcase?:
    | {
        eyebrow?: string | null;
        title: string;
        desc: string;
        bullets?:
          | {
              text: string;
              id?: string | null;
            }[]
          | null;
        /**
         * Yatay ekran görseli (4:3).
         */
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * İkonlu kartlar; altı özellik önerilir.
   */
  features?:
    | {
        title: string;
        icon:
          | 'share'
          | 'palette'
          | 'pen'
          | 'monitor'
          | 'chart-bar'
          | 'clapperboard'
          | 'bot'
          | 'users'
          | 'workflow'
          | 'briefcase'
          | 'message'
          | 'brain'
          | 'languages'
          | 'bell'
          | 'calendar'
          | 'clipboard'
          | 'database'
          | 'file'
          | 'gauge'
          | 'handshake'
          | 'kanban'
          | 'dashboard'
          | 'layers'
          | 'link'
          | 'pie'
          | 'shield'
          | 'sparkles'
          | 'target'
          | 'rocket'
          | 'megaphone'
          | 'camera'
          | 'globe'
          | 'cart'
          | 'search'
          | 'mail'
          | 'zap'
          | 'trending'
          | 'code'
          | 'lightbulb'
          | 'award'
          | 'badge-check'
          | 'gem'
          | 'chart-line';
        desc: string;
        id?: string | null;
      }[]
    | null;
  /**
   * İki sütun; dört madde önerilir.
   */
  comparison?: {
    before?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    after?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Numaralı kartlar; dört adım önerilir.
   */
  steps?:
    | {
        title: string;
        desc: string;
        id?: string | null;
      }[]
    | null;
  useCases?:
    | {
        title: string;
        desc: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Yalnız ürün ve kurulum gerçekleri (kanal sayısı, kurulum süresi). Kaynağı olmayan performans rakamı yazmayın.
   */
  stats?:
    | {
        value: number;
        /**
         * %, /24, gün…
         */
        suffix?: string | null;
        label: string;
        id?: string | null;
      }[]
    | null;
  included?:
    | {
        title: string;
        icon:
          | 'share'
          | 'palette'
          | 'pen'
          | 'monitor'
          | 'chart-bar'
          | 'clapperboard'
          | 'bot'
          | 'users'
          | 'workflow'
          | 'briefcase'
          | 'message'
          | 'brain'
          | 'languages'
          | 'bell'
          | 'calendar'
          | 'clipboard'
          | 'database'
          | 'file'
          | 'gauge'
          | 'handshake'
          | 'kanban'
          | 'dashboard'
          | 'layers'
          | 'link'
          | 'pie'
          | 'shield'
          | 'sparkles'
          | 'target'
          | 'rocket'
          | 'megaphone'
          | 'camera'
          | 'globe'
          | 'cart'
          | 'search'
          | 'mail'
          | 'zap'
          | 'trending'
          | 'code'
          | 'lightbulb'
          | 'award'
          | 'badge-check'
          | 'gem'
          | 'chart-line';
        desc: string;
        id?: string | null;
      }[]
    | null;
  integrations?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Sayfada iki sütunlu akordeon olarak görünür ve arama motorlarına SSS olarak bildirilir.
   */
  faq?:
    | {
        q: string;
        a: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Ana sayfa ve ürün kartlarındaki dikey kapak (4:5).
   */
  cover?: (number | null) | Media;
  /**
   * Ürünler sayfasındaki kartta tik işaretiyle; üç madde önerilir.
   */
  highlights?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Yatay ürün ekranı; kapak yoksa kartlarda bunun yerine kullanılır.
   */
  screenshot: number | Media;
  /**
   * Bağlantı WhatsApp ya da sosyal medyada paylaşılınca görünen görsel. Boşsa ürünün hazır paylaşım görseli kullanılır.
   */
  ogImage?: (number | null) | Media;
  seo?: {
    /**
     * Google'da mavi başlık. Boşsa ürün adı ve slogan.
     */
    title?: string | null;
    /**
     * Başlığın altındaki iki satır.
     */
    description?: string | null;
    keywords?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Sayfa adresi: /urunler/adres. Yayındaki bir adresi değiştirmek eski bağlantıları kırar.
   */
  slug?: string | null;
  /**
   * Küçük sayı önce gelir (menü, kartlar, alt bilgi).
   */
  order?: number | null;
  icon:
    | 'share'
    | 'palette'
    | 'pen'
    | 'monitor'
    | 'chart-bar'
    | 'clapperboard'
    | 'bot'
    | 'users'
    | 'workflow'
    | 'briefcase'
    | 'message'
    | 'brain'
    | 'languages'
    | 'bell'
    | 'calendar'
    | 'clipboard'
    | 'database'
    | 'file'
    | 'gauge'
    | 'handshake'
    | 'kanban'
    | 'dashboard'
    | 'layers'
    | 'link'
    | 'pie'
    | 'shield'
    | 'sparkles'
    | 'target'
    | 'rocket'
    | 'megaphone'
    | 'camera'
    | 'globe'
    | 'cart'
    | 'search'
    | 'mail'
    | 'zap'
    | 'trending'
    | 'code'
    | 'lightbulb'
    | 'award'
    | 'badge-check'
    | 'gem'
    | 'chart-line';
  /**
   * Paket ürünlerde (ör. Guru Business) sayfada "Pakete dahil" bölümü olarak görünür.
   */
  bundle?: (number | Product)[] | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  /**
   * Liste kartında ve paylaşımlarda görünen 1-2 cümle.
   */
  excerpt: string;
  /**
   * Yatay görsel önerilir (en az 1600 px genişlik).
   */
  cover?: (number | null) | Media;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Boş bırakırsanız başlıktan üretilir: /blog/adres
   */
  slug?: string | null;
  category?: (number | null) | Category;
  /**
   * Boş bırakılırsa yayınlandığı an yazılır.
   */
  publishedAt?: string | null;
  author?: (number | null) | User;
  /**
   * Boş bırakılırsa başlık ve özet kullanılır.
   */
  seo?: {
    title?: string | null;
    description?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  title: string;
  /**
   * Boş bırakırsanız addan üretilir.
   */
  slug?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'leads';
        value: number | Lead;
      } | null)
    | ({
        relationTo: 'bookings';
        value: number | Booking;
      } | null)
    | ({
        relationTo: 'deals';
        value: number | Deal;
      } | null)
    | ({
        relationTo: 'contacts';
        value: number | Contact;
      } | null)
    | ({
        relationTo: 'companies';
        value: number | Company;
      } | null)
    | ({
        relationTo: 'quotes';
        value: number | Quote;
      } | null)
    | ({
        relationTo: 'activities';
        value: number | Activity;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'tasks';
        value: number | Task;
      } | null)
    | ({
        relationTo: 'templates';
        value: number | Template;
      } | null)
    | ({
        relationTo: 'conversations';
        value: number | Conversation;
      } | null)
    | ({
        relationTo: 'knowledge';
        value: number | Knowledge;
      } | null)
    | ({
        relationTo: 'chat-messages';
        value: number | ChatMessage;
      } | null)
    | ({
        relationTo: 'team';
        value: number | Team;
      } | null)
    | ({
        relationTo: 'case-studies';
        value: number | CaseStudy;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'references';
        value: number | Reference;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'tenants';
        value: number | Tenant;
      } | null)
    | ({
        relationTo: 'payload-folders';
        value: number | FolderInterface;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads_select".
 */
export interface LeadsSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  phone?: T;
  service?: T;
  subject?: T;
  message?: T;
  status?: T;
  source?: T;
  contact?: T;
  deal?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bookings_select".
 */
export interface BookingsSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  phone?: T;
  date?: T;
  time?: T;
  topic?: T;
  note?: T;
  status?: T;
  slot?: T;
  source?: T;
  contact?: T;
  deal?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "deals_select".
 */
export interface DealsSelect<T extends boolean = true> {
  title?: T;
  contact?: T;
  company?: T;
  value?: T;
  expectedClose?: T;
  service?: T;
  lostReason?: T;
  notes?: T;
  stage?: T;
  owner?: T;
  lead?: T;
  closedAt?: T;
  order?: T;
  tenant?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contacts_select".
 */
export interface ContactsSelect<T extends boolean = true> {
  name?: T;
  title?: T;
  email?: T;
  phone?: T;
  company?: T;
  notes?: T;
  source?: T;
  tags?: T;
  owner?: T;
  tenant?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "companies_select".
 */
export interface CompaniesSelect<T extends boolean = true> {
  name?: T;
  sector?: T;
  website?: T;
  phone?: T;
  email?: T;
  address?: T;
  taxOffice?: T;
  taxNumber?: T;
  notes?: T;
  owner?: T;
  tenant?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quotes_select".
 */
export interface QuotesSelect<T extends boolean = true> {
  title?: T;
  deal?: T;
  contact?: T;
  company?: T;
  items?:
    | T
    | {
        description?: T;
        qty?: T;
        unit?: T;
        unitPrice?: T;
        vatRate?: T;
        id?: T;
      };
  notes?: T;
  terms?: T;
  number?: T;
  status?: T;
  issueDate?: T;
  validUntil?: T;
  subtotal?: T;
  vatTotal?: T;
  total?: T;
  owner?: T;
  tenant?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "activities_select".
 */
export interface ActivitiesSelect<T extends boolean = true> {
  type?: T;
  title?: T;
  body?: T;
  dueAt?: T;
  done?: T;
  deal?: T;
  contact?: T;
  company?: T;
  booking?: T;
  owner?: T;
  tenant?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  title?: T;
  company?: T;
  contact?: T;
  startDate?: T;
  dueDate?: T;
  template?: T;
  description?: T;
  status?: T;
  owner?: T;
  deal?: T;
  tenant?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tasks_select".
 */
export interface TasksSelect<T extends boolean = true> {
  title?: T;
  project?: T;
  assignee?: T;
  startDate?: T;
  dueDate?: T;
  hours?: T;
  description?: T;
  checklist?:
    | T
    | {
        done?: T;
        text?: T;
        id?: T;
      };
  stage?: T;
  priority?: T;
  seq?: T;
  startedAt?: T;
  completedAt?: T;
  order?: T;
  tenant?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "templates_select".
 */
export interface TemplatesSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  steps?:
    | T
    | {
        title?: T;
        assignee?: T;
        offset?: T;
        duration?: T;
        hours?: T;
        priority?: T;
        checklist?:
          | T
          | {
              text?: T;
              id?: T;
            };
        id?: T;
      };
  tenant?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "conversations_select".
 */
export interface ConversationsSelect<T extends boolean = true> {
  label?: T;
  name?: T;
  email?: T;
  phone?: T;
  topic?: T;
  page?: T;
  lastText?: T;
  status?: T;
  needsReply?: T;
  assignee?: T;
  contact?: T;
  lead?: T;
  booking?: T;
  lastMessageAt?: T;
  handedOffAt?: T;
  firstTeamReplyAt?: T;
  visitorMessages?: T;
  token?: T;
  tenant?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "knowledge_select".
 */
export interface KnowledgeSelect<T extends boolean = true> {
  title?: T;
  content?: T;
  active?: T;
  tenant?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "chat-messages_select".
 */
export interface ChatMessagesSelect<T extends boolean = true> {
  conversation?: T;
  role?: T;
  text?: T;
  author?: T;
  unanswered?: T;
  tenant?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team_select".
 */
export interface TeamSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  photo?: T;
  linkedin?: T;
  order?: T;
  showOnHome?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "case-studies_select".
 */
export interface CaseStudiesSelect<T extends boolean = true> {
  sector?: T;
  title?: T;
  summary?: T;
  stats?:
    | T
    | {
        label?: T;
        value?: T;
        prefix?: T;
        suffix?: T;
        featured?: T;
        id?: T;
      };
  note?: T;
  order?: T;
  showOnHome?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  quote?: T;
  name?: T;
  title?: T;
  company?: T;
  photo?: T;
  consent?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "references_select".
 */
export interface ReferencesSelect<T extends boolean = true> {
  name?: T;
  logo?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  title?: T;
  short?: T;
  menuDesc?: T;
  cardImage?: T;
  gallery?:
    | T
    | {
        image?: T;
        id?: T;
      };
  headline?: T;
  offeringsTitle?: T;
  intro?:
    | T
    | {
        text?: T;
        id?: T;
      };
  offerings?:
    | T
    | {
        text?: T;
        id?: T;
      };
  keywords?:
    | T
    | {
        text?: T;
        id?: T;
      };
  faq?:
    | T
    | {
        q?: T;
        a?: T;
        id?: T;
      };
  showCases?: T;
  showWebProjects?: T;
  seoDescription?: T;
  slug?: T;
  order?: T;
  icon?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  name?: T;
  tagline?: T;
  desc?: T;
  hero?:
    | T
    | {
        eyebrow?: T;
        headline?: T;
        sub?: T;
        ctaLabel?: T;
        trust?:
          | T
          | {
              text?: T;
              id?: T;
            };
      };
  heroVisual?: T;
  tour?:
    | T
    | {
        show?: T;
        title?: T;
        videoUrl?: T;
        poster?: T;
      };
  showcase?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        desc?: T;
        bullets?:
          | T
          | {
              text?: T;
              id?: T;
            };
        image?: T;
        id?: T;
      };
  features?:
    | T
    | {
        title?: T;
        icon?: T;
        desc?: T;
        id?: T;
      };
  comparison?:
    | T
    | {
        before?:
          | T
          | {
              text?: T;
              id?: T;
            };
        after?:
          | T
          | {
              text?: T;
              id?: T;
            };
      };
  steps?:
    | T
    | {
        title?: T;
        desc?: T;
        id?: T;
      };
  useCases?:
    | T
    | {
        title?: T;
        desc?: T;
        id?: T;
      };
  stats?:
    | T
    | {
        value?: T;
        suffix?: T;
        label?: T;
        id?: T;
      };
  included?:
    | T
    | {
        title?: T;
        icon?: T;
        desc?: T;
        id?: T;
      };
  integrations?:
    | T
    | {
        text?: T;
        id?: T;
      };
  faq?:
    | T
    | {
        q?: T;
        a?: T;
        id?: T;
      };
  cover?: T;
  highlights?:
    | T
    | {
        text?: T;
        id?: T;
      };
  screenshot?: T;
  ogImage?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        keywords?:
          | T
          | {
              text?: T;
              id?: T;
            };
      };
  slug?: T;
  order?: T;
  icon?: T;
  bundle?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  excerpt?: T;
  cover?: T;
  content?: T;
  slug?: T;
  category?: T;
  publishedAt?: T;
  author?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  prefix?: T;
  _objectKey?: T;
  folder?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        wide?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  weeklyHours?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants_select".
 */
export interface TenantsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders_select".
 */
export interface PayloadFoldersSelect<T extends boolean = true> {
  name?: T;
  folder?: T;
  documentsAndFolders?: T;
  folderType?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Kaydettiğinizde ana sayfa hemen güncellenir.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page".
 */
export interface HomePage {
  id: number;
  hero: {
    title: string;
    sub: string;
    showServiceLinks?: boolean | null;
    primaryLabel: string;
    primaryHref: string;
    secondaryLabel: string;
    secondaryHref: string;
    badgeStrong?: string | null;
    badgeText?: string | null;
  };
  references: {
    show?: boolean | null;
    title: string;
    lead?: string | null;
  };
  services: {
    show?: boolean | null;
    title: string;
    lead?: string | null;
  };
  products: {
    show?: boolean | null;
    title: string;
    lead?: string | null;
  };
  video: {
    show?: boolean | null;
    title: string;
    lead?: string | null;
  };
  cases: {
    show?: boolean | null;
    title: string;
    lead?: string | null;
  };
  team: {
    show?: boolean | null;
    title: string;
    lead?: string | null;
    /**
     * Ekip kayıtlarında "Ana sayfada göster" seçili olanlar sırayla gösterilir.
     */
    limit?: number | null;
  };
  quotes: {
    show?: boolean | null;
    title: string;
    lead?: string | null;
  };
  faq: {
    show?: boolean | null;
    title: string;
    items?:
      | {
          q: string;
          a: string;
          id?: string | null;
        }[]
      | null;
  };
  meet: {
    title: string;
    text: string;
    buttonLabel: string;
    buttonHref: string;
  };
  seo?: {
    title?: string | null;
    description?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Kaydettiğinizde Hakkımızda sayfası ve ödüllerin geçtiği yerler güncellenir.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page".
 */
export interface AboutPage {
  id: number;
  intro: {
    eyebrow?: string | null;
    title: string;
    lead?: string | null;
    primaryLabel: string;
    primaryHref: string;
    secondaryLabel?: string | null;
    secondaryHref?: string | null;
  };
  story: {
    title: string;
    paragraphs?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    valuesLabel?: string | null;
    values?:
      | {
          title: string;
          icon:
            | 'share'
            | 'palette'
            | 'pen'
            | 'monitor'
            | 'chart-bar'
            | 'clapperboard'
            | 'bot'
            | 'users'
            | 'workflow'
            | 'briefcase'
            | 'message'
            | 'brain'
            | 'languages'
            | 'bell'
            | 'calendar'
            | 'clipboard'
            | 'database'
            | 'file'
            | 'gauge'
            | 'handshake'
            | 'kanban'
            | 'dashboard'
            | 'layers'
            | 'link'
            | 'pie'
            | 'shield'
            | 'sparkles'
            | 'target'
            | 'rocket'
            | 'megaphone'
            | 'camera'
            | 'globe'
            | 'cart'
            | 'search'
            | 'mail'
            | 'zap'
            | 'trending'
            | 'code'
            | 'lightbulb'
            | 'award'
            | 'badge-check'
            | 'gem'
            | 'chart-line';
          desc: string;
          id?: string | null;
        }[]
      | null;
  };
  awards: {
    show?: boolean | null;
    title: string;
    lead?: string | null;
    /**
     * İlk ödül alt bilgideki rozette de görünür (ör. 2025 Google Partner).
     */
    items?:
      | {
          title: string;
          year: string;
          badge?: string | null;
          icon:
            | 'share'
            | 'palette'
            | 'pen'
            | 'monitor'
            | 'chart-bar'
            | 'clapperboard'
            | 'bot'
            | 'users'
            | 'workflow'
            | 'briefcase'
            | 'message'
            | 'brain'
            | 'languages'
            | 'bell'
            | 'calendar'
            | 'clipboard'
            | 'database'
            | 'file'
            | 'gauge'
            | 'handshake'
            | 'kanban'
            | 'dashboard'
            | 'layers'
            | 'link'
            | 'pie'
            | 'shield'
            | 'sparkles'
            | 'target'
            | 'rocket'
            | 'megaphone'
            | 'camera'
            | 'globe'
            | 'cart'
            | 'search'
            | 'mail'
            | 'zap'
            | 'trending'
            | 'code'
            | 'lightbulb'
            | 'award'
            | 'badge-check'
            | 'gem'
            | 'chart-line';
          desc: string;
          image?: (number | null) | Media;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Kişiler "Kurumsal > Ekip"ten gelir.
   */
  team: {
    show?: boolean | null;
    title: string;
    lead?: string | null;
  };
  /**
   * Sayılar referans, hizmet ve ürün kayıtlarından otomatik hesaplanır.
   */
  stats: {
    show?: boolean | null;
    title: string;
    referencesLabel?: string | null;
    servicesLabel?: string | null;
    productsLabel?: string | null;
  };
  closing: {
    title: string;
    lead?: string | null;
    primaryLabel: string;
  };
  seo?: {
    title?: string | null;
    description?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "chatbot-settings".
 */
export interface ChatbotSetting {
  id: number;
  /**
   * Açınca sitenin sağ alt köşesinde sohbet balonu çıkar. Yapay zekâ anahtarı yoksa mesajlar doğrudan ekibe düşer.
   */
  enabled?: boolean | null;
  botName: string;
  model?: ('claude-haiku-5-5' | 'claude-sonnet-5-5') | null;
  greeting?: string | null;
  /**
   * Sohbet açılınca ziyaretçiye dokunulabilir öneri olarak görünür.
   */
  suggestions?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Sohbet penceresinin altında küçük yazıyla görünür. KVKK aydınlatma metni gelince bağlantısı eklenir.
   */
  notice?: string | null;
  /**
   * Ton, vurgulanacak kampanya ya da yanıtlanmayacak konular. Ör. "Ekim boyunca web sitesi projelerinde ücretsiz keşif görüşmesi var."
   */
  instructions?: string | null;
  /**
   * Gelen kutusunda tek tıkla eklenen kısa yanıtlar.
   */
  cannedReplies?:
    | {
        label: string;
        text: string;
        id?: string | null;
      }[]
    | null;
  notifyHandoff?: boolean | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  announcement?: {
    enabled?: boolean | null;
    text?: string | null;
  };
  contact?: {
    email?: string | null;
    phone?: string | null;
    /**
     * Ülke koduyla; doldurulunca sağdaki sekme WhatsApp'a gider.
     */
    whatsapp?: string | null;
    instagram?: string | null;
    address?: string | null;
  };
  /**
   * Çerezsiz, kişisel veri toplamayan ziyaretçi sayımı. Bu alanlar sitenin her sayfasına bir betik eklediği için yalnız yöneticiler düzenleyebilir. API bağlantısı (panel istatistikleri) sunucu ortam değişkenlerindedir.
   */
  analytics?: {
    enabled?: boolean | null;
    websiteId?: string | null;
    scriptUrl?: string | null;
    /**
     * Virgülle ayırın. Doluysa önizleme ve yerel adresler sayılmaz.
     */
    domains?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        title?: T;
        sub?: T;
        showServiceLinks?: T;
        primaryLabel?: T;
        primaryHref?: T;
        secondaryLabel?: T;
        secondaryHref?: T;
        badgeStrong?: T;
        badgeText?: T;
      };
  references?:
    | T
    | {
        show?: T;
        title?: T;
        lead?: T;
      };
  services?:
    | T
    | {
        show?: T;
        title?: T;
        lead?: T;
      };
  products?:
    | T
    | {
        show?: T;
        title?: T;
        lead?: T;
      };
  video?:
    | T
    | {
        show?: T;
        title?: T;
        lead?: T;
      };
  cases?:
    | T
    | {
        show?: T;
        title?: T;
        lead?: T;
      };
  team?:
    | T
    | {
        show?: T;
        title?: T;
        lead?: T;
        limit?: T;
      };
  quotes?:
    | T
    | {
        show?: T;
        title?: T;
        lead?: T;
      };
  faq?:
    | T
    | {
        show?: T;
        title?: T;
        items?:
          | T
          | {
              q?: T;
              a?: T;
              id?: T;
            };
      };
  meet?:
    | T
    | {
        title?: T;
        text?: T;
        buttonLabel?: T;
        buttonHref?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page_select".
 */
export interface AboutPageSelect<T extends boolean = true> {
  intro?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        lead?: T;
        primaryLabel?: T;
        primaryHref?: T;
        secondaryLabel?: T;
        secondaryHref?: T;
      };
  story?:
    | T
    | {
        title?: T;
        paragraphs?:
          | T
          | {
              text?: T;
              id?: T;
            };
        valuesLabel?: T;
        values?:
          | T
          | {
              title?: T;
              icon?: T;
              desc?: T;
              id?: T;
            };
      };
  awards?:
    | T
    | {
        show?: T;
        title?: T;
        lead?: T;
        items?:
          | T
          | {
              title?: T;
              year?: T;
              badge?: T;
              icon?: T;
              desc?: T;
              image?: T;
              id?: T;
            };
      };
  team?:
    | T
    | {
        show?: T;
        title?: T;
        lead?: T;
      };
  stats?:
    | T
    | {
        show?: T;
        title?: T;
        referencesLabel?: T;
        servicesLabel?: T;
        productsLabel?: T;
      };
  closing?:
    | T
    | {
        title?: T;
        lead?: T;
        primaryLabel?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "chatbot-settings_select".
 */
export interface ChatbotSettingsSelect<T extends boolean = true> {
  enabled?: T;
  botName?: T;
  model?: T;
  greeting?: T;
  suggestions?:
    | T
    | {
        text?: T;
        id?: T;
      };
  notice?: T;
  instructions?: T;
  cannedReplies?:
    | T
    | {
        label?: T;
        text?: T;
        id?: T;
      };
  notifyHandoff?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  announcement?:
    | T
    | {
        enabled?: T;
        text?: T;
      };
  contact?:
    | T
    | {
        email?: T;
        phone?: T;
        whatsapp?: T;
        instagram?: T;
        address?: T;
      };
  analytics?:
    | T
    | {
        enabled?: T;
        websiteId?: T;
        scriptUrl?: T;
        domains?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}